BotmanSite/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from BotmanSite import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('avatar', include('avatar.urls')),
    url(r'', include(('website.urls', 'website'), namespace='website')),
]

website/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import RedirectView

from website import views

urlpatterns = [
    path('dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard/data', views.dashboard_data, name='dashboard_data'),
    path('chats', views.Chats.as_view(), name='chats'),
    path('distribution', views.Distribution.as_view(), name='distribution'),
    path('distribution/start', views.start_distribution_view, name='start_distribution'),
    path('users', views.Users.as_view(), name='users'),
    path('users/data', views.users_data, name='users_data'),
    path('notifications', views.Notifications.as_view(), name='notifications'),
    path('control', views.Control.as_view(), name='control'),
    path('control/start_bot', views.start_bot_view, name='start_bot'),
    path('control/stop_bot', views.stop_bot_view, name='stop_bot'),
    path('control/restart_bot', views.restart_bot_view, name='restart_bot'),
    path('control/bot_status', views.bot_status_view, name='bot_status'),
    path('control/api_status', views.api_status_view, name='api_status'),
    path('profile', views.Profile.as_view(), name='profile'),
    path('change_bot', views.change_bot, name='change_bot'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
    url(r'^.*$', RedirectView.as_view(url='/dashboard', permanent=False), name='dashboard')
]

website/models.py
import binascii
import hashlib
import json
import os

import requests
from avatar.models import AvatarField
from django.contrib.auth.models import AbstractUser
from django.core.files.storage import get_storage_class
from django.db import models
from django.utils.encoding import force_bytes
from django.utils.translation import ugettext as _
from avatar.conf import settings


def bot_avatar_path_handler(instance=None, filename=None, size=None, ext=None):
    tmppath = [settings.AVATAR_STORAGE_DIR]
    tmppath.append(instance.name)
    if not filename:
        # Filename already stored in database
        filename = instance.avatar.name
        if ext and settings.AVATAR_HASH_FILENAMES:
            # An extension was provided, probably because the thumbnail
            # is in a different format than the file. Use it. Because it's
            # only enabled if AVATAR_HASH_FILENAMES is true, we can trust
            # it won't conflict with another filename
            (root, oldext) = os.path.splitext(filename)
            filename = root + "." + ext
    else:
        # File doesn't exist yet
        if settings.AVATAR_HASH_FILENAMES:
            (root, ext) = os.path.splitext(filename)
            if settings.AVATAR_RANDOMIZE_HASHES:
                filename = binascii.hexlify(os.urandom(16)).decode('ascii')
            else:
                filename = hashlib.md5(force_bytes(filename)).hexdigest()
            filename = filename + ext
    if size:
        tmppath.extend(['resized', str(size)])
    tmppath.append(os.path.basename(filename))
    return os.path.join(*tmppath)


avatar_storage = get_storage_class(settings.AVATAR_STORAGE)()


class BotAvatarField(models.ImageField):

    def __init__(self, *args, **kwargs):
        super(BotAvatarField, self).__init__(*args, **kwargs)

        self.max_length = 1024
        self.upload_to = bot_avatar_path_handler
        self.storage = avatar_storage
        self.blank = True

    def deconstruct(self):
        name, path, args, kwargs = super(models.ImageField, self).deconstruct()
        return name, path, (), {}


class Bot(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=32)
    token = models.CharField(max_length=128)
    domain = models.URLField(verbose_name="Api url")
    create_date = models.DateTimeField(auto_now=True)
    avatar = BotAvatarField(verbose_name=_("avatar"))
    users = models.ManyToManyField("User", blank=True, related_name='bots')

    def __str__(self):
        return self.name

    def _headers(self):
        return {"X-API-KEY": self.token}

    def get_domain(self):
        if self.domain.endswith('/'):
            return self.domain
        else:
            return self.domain + '/'

    def get_api_status(self):
        endpoint = self.get_domain() + 'status'
        try:
            # TODO: verify SSL
            # res = requests.get(endpoint, verify=path.join(PROJECT_PATH, 'botmanCA.pem'))
            res = requests.get(endpoint, verify=False)
            if res.status_code == 200:
                content = json.loads(res.content.decode('utf-8'))
                return content.get('status')
            else:
                return False
        except requests.exceptions.ConnectionError:
            return False

    def get_bot_status(self):
        endpoint = self.get_domain() + 'bot/status'
        try:
            # TODO: verify SSL
            # res = requests.get(endpoint, verify=path.join(PROJECT_PATH, 'botmanCA.pem'))
            res = requests.get(endpoint, headers=self._headers(), verify=False)
            if res.status_code == 200:
                content = json.loads(res.content.decode('utf-8'))
                return content.get('status')
            else:
                return False
        except requests.exceptions.ConnectionError:
            return False


class User(AbstractUser):

    def get_selected_bot(self, session):
        selected_bot = session.get('selected_bot')

        if selected_bot is None:
            user_bots = self.bots.all()
            if user_bots:
                bot = user_bots[0]
                session['selected_bot'] = bot.id
            else:
                bot = None
        else:
            try:
                bot = Bot.objects.get(pk=selected_bot)
            except Bot.DoesNotExist:
                bot = None

        return bot

website/forms.py
import os

from avatar.models import Avatar
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from avatar.conf import settings as avatar_settings
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _

from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = User
        fields = ('email', 'first_name', 'last_name')

    avatar = forms.ImageField(label=_("avatar"), required=False)

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        if 'instance' in kwargs and isinstance(kwargs['instance'], User):
            self.user = kwargs['instance']

        super(CustomUserChangeForm, self).__init__(*args, **kwargs)

    def clean_avatar(self):
        data = self.cleaned_data['avatar']

        if avatar_settings.AVATAR_ALLOWED_FILE_EXTS:
            root, ext = os.path.splitext(data.name.lower())
            if ext not in avatar_settings.AVATAR_ALLOWED_FILE_EXTS:
                valid_exts = ", ".join(avatar_settings.AVATAR_ALLOWED_FILE_EXTS)
                error = _("%(ext)s is an invalid file extension. "
                          "Authorized extensions are : %(valid_exts_list)s")
                raise forms.ValidationError(error %
                                            {'ext': ext,
                                             'valid_exts_list': valid_exts})

        if data and data.size > avatar_settings.AVATAR_MAX_SIZE:
            error = _("Your file is too big (%(size)s), "
                      "the maximum allowed size is %(max_valid_size)s")
            raise forms.ValidationError(error % {
                'size': filesizeformat(data.size),
                'max_valid_size': filesizeformat(avatar_settings.AVATAR_MAX_SIZE)
            })

        count = Avatar.objects.filter(user=self.user).count()
        if 1 < avatar_settings.AVATAR_MAX_AVATARS_PER_USER <= count:
            error = _("You already have %(nb_avatars)d avatars, "
                      "and the maximum allowed is %(nb_max_avatars)d.")
            raise forms.ValidationError(error % {
                'nb_avatars': count,
                'nb_max_avatars': avatar_settings.AVATAR_MAX_AVATARS_PER_USER,
            })
        return

website/views.py
from asgiref.sync import async_to_sync
from avatar.models import Avatar
from avatar.signals import avatar_updated
from avatar.views import _get_avatars
from channels.layers import get_channel_layer
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import TemplateView

from website import tasks
from website.forms import CustomUserChangeForm


class NamedPageMixin:
    page_name = _("Unnamed")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_name'] = getattr(self, 'page_name', None)
        context["page_full_name"] = getattr(self, 'page_full_name', None)
        return context


class Dashboard(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'dashboard.html'
    page_name = _("Dashboard")


class Chats(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'chats.html'
    page_name = _("Chats")


class Distribution(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'distribution.html'
    page_name = _("Distribution")


class Control(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/control'
    template_name = 'control.html'
    page_name = _("Control")


class Users(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'users.html'
    page_name = _("Users")


class Profile(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/profile'
    template_name = 'profile.html'
    page_full_name = _("Profile")

    def post(self, request, *args, **kwargs):
        avatar, avatars = _get_avatars(request.user)

        change_user_form = CustomUserChangeForm(request.POST or None,
                                                request.FILES or None,
                                                user=request.user,
                                                instance=request.user)

        if change_user_form.is_valid():
            if 'avatar' in request.FILES:
                avatar = Avatar(user=request.user, primary=True)
                image_file = request.FILES['avatar']
                avatar.avatar.save(image_file.name, image_file)
                avatar.save()
                avatar_updated.send(sender=Avatar, user=request.user, avatar=avatar)
            change_user_form.save()

        context = self.get_context_data()
        return render(request, self.template_name, context)


class Notifications(NamedPageMixin, LoginRequiredMixin, TemplateView):
    login_url = '/login'
    template_name = 'notifications.html'
    page_name = _("Notifications")


class Login(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(request.GET.get("next", '/dashboard'))
        else:
            return render(request, self.template_name, {"message": ""})

    def post(self, request, *args, **kwargs):
        username = request.POST.get("login", None)
        password = request.POST.get("password", None)
        next = request.POST.get("next", "")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if len(user.bots.all()):
                request.session['selected_bot'] = user.bots.all()[0].id
            else:
                request.session['selected_bot'] = 0
            return HttpResponseRedirect(next)
        return render(request, self.template_name, {"message": "Wrong username or password"})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login')


@login_required
def change_bot(request, *args, **kwargs):
    bot_id = request.GET.get('bot', None)
    # next = request.GET.get('next', '/dashboard')
    try:
        bot_id = int(bot_id)
    except ValueError:
        bot_id = None

    if bot_id is None:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    # TODO: Optimize query
    user_bots = request.user.bots.all()
    selected_bot = None
    for bot in user_bots:
        if bot_id == bot.id:
            selected_bot = bot
            break
    if selected_bot:
        request.session['selected_bot'] = int(bot_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def start_bot_view(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)
    if bot:
        tasks.start_bot.delay(request.user.id, bot.get_domain(), bot.token)
    else:
        cl = get_channel_layer()
        async_to_sync(cl.group_send)(f"user-{request.user.id}-notification", {'type': 'receive', 'notification': {'type': 'warning', 'text': "Bot not selected"}})

    return JsonResponse({})


@login_required
def stop_bot_view(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)
    tasks.stop_bot.delay(request.user.id, bot.get_domain(), bot.token)
    return JsonResponse({})


@login_required
def restart_bot_view(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)
    tasks.restart_bot.delay(request.user.id, bot.get_domain(), bot.token)
    return JsonResponse({})


@login_required
def start_distribution_view(request, *args, **kwargs):
    if request.method:
        bot = request.user.get_selected_bot(request.session)

        text = request.POST.get("text", None)
        when = None
        web_preview = request.POST.get("web-preview", False) == 'on'
        notification = request.POST.get("notification", False) == 'on'

        cl = get_channel_layer()
        if bot:
            if text:
                tasks.bot_distribution.delay(request.user.id, bot.get_domain(), bot.token, text, when, web_preview, notification)
                return JsonResponse({"success": True})
            else:
                async_to_sync(cl.group_send)(f"user-{request.user.id}-notification", {'type': 'receive', 'notification': {'type': 'warning', 'text': "Please enter a message"}})

        else:
            async_to_sync(cl.group_send)(f"user-{request.user.id}-notification", {'type': 'receive', 'notification': {'type': 'warning', 'text': "Bot not selected"}})
        return JsonResponse({"success": False})


@login_required
def bot_status_view(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)

    if bot:
        tasks.get_bot_status.delay(request.user.id, bot.get_domain(), bot.token)
    else:
        cl = get_channel_layer()
        async_to_sync(cl.group_send)(f"user-{request.user.id}-control", {'type': 'receive', 'service': 'bot', "status": False})

    return JsonResponse({})


@login_required
def api_status_view(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)

    if bot:
        tasks.get_api_status.delay(request.user.id, bot.get_domain(), bot.token)
    else:
        cl = get_channel_layer()
        async_to_sync(cl.group_send)(f"user-{request.user.id}-control", {'type': 'receive', 'service': 'api', "status": False})

    return JsonResponse({})


@login_required
def dashboard_data(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)

    if bot:
        tasks.get_uptime.delay(request.user.id, bot.get_domain(), bot.token, 'dashboard')
        tasks.get_start_date.delay(request.user.id, bot.get_domain(), bot.token, 'dashboard')
        tasks.get_stats.delay(request.user.id, bot.get_domain(), bot.token, 'dashboard')
        tasks.get_users.delay(request.user.id, bot.get_domain(), bot.token, 'dashboard')

    else:
        cl = get_channel_layer()
        async_to_sync(cl.group_send)(f"user-{request.user.id}-dashboard", {'type': 'receive', 'task': None, 'data': False})

    return JsonResponse({})


@login_required
def users_data(request, *args, **kwargs):
    bot = request.user.get_selected_bot(request.session)

    if bot:
        tasks.get_stats.delay(request.user.id, bot.get_domain(), bot.token, 'users')
        tasks.get_users.delay(request.user.id, bot.get_domain(), bot.token, 'users')

    else:
        cl = get_channel_layer()
        async_to_sync(cl.group_send)(f"user-{request.user.id}-users", {'type': 'receive', 'task': None, 'data': False})

    return JsonResponse({})

website/templates/control.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
     <div class="row">
            <div class="col-lg-6 col-md-12 col-sm-12 pl-1 pr-1">
              <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <p class="card-category">{% trans "API Status" %}</p>
                    <div id="api_status" class="card-title">
                        <h3 class="float-left text-success">{% trans "Loading..." %}</h3>
                    </div>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">sync</i> {% trans "Last restart" %}: 22.08.2019 10:34
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 pl-1 pr-1">
              <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <p class="card-category">{% trans "Bot Status" %}</p>
                    <div id="bot_status" class="card-title">
                        <h3 class="float-left text-success">{% trans "Loading..." %}</h3>
                    </div>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">sync</i> {% trans "Started" context "When bot was started" %}: 22.08.2019 10:34
                  </div>
                </div>
              </div>
            </div>
     </div>
{% endblock %}
{% block js %}
{{ block.super }}
<script>
function start_bot(){
    $.ajax({
        url: '{% url "website:start_bot" %}',
        method: "GET",
        dataType: 'json',
      });
    }
function stop_bot(){
    $.ajax({
        url: '{% url "website:stop_bot" %}',
        method: "GET",
        dataType: 'json',
      });
    }
function restart_bot(){
    $.ajax({
        url: '{% url "website:restart_bot" %}',
        method: "GET",
        dataType: 'json',
      });
    }
var socket = new WebSocket(ws_scheme + "://" + window.location.host + "/ws/control");
socket.onmessage = function (e) {
    let data = JSON.parse(e.data);
    console.log(data);
    let bot_status_element = $("#bot_status");
    let api_status_element = $("#api_status");
    if (data['service'] === 'api'){
        if (data['status'] === false){
            api_status_element.empty();
            api_status_element.append("<h3 class=\"float-left text-danger\">{% trans "Stopped" context "Api current status" %}</h3>");
        }
        else{
            api_status_element.empty();
            api_status_element.append("<h3 class=\"float-left text-success\">{% trans "Running" context "Api current status" %}");
        }
    }
    else if (data['service'] === 'bot'){
        if (data['status'] === false){
            bot_status_element.empty();
            bot_status_element.append("<h3 class=\"float-left text-danger\">{% trans "Stopped" context "Bot current status" %}</h3>");
            let buttons_block = $('<div />', {"class": 'button-container float-right mt-3'});
            buttons_block.append("<a class=\"btn btn-primary mb-0 mt-0 pl-2 pr-2\" href=\"#\" onclick=\"start_bot()\">{% trans "Start" context "Button for starting bot" %}</a>");
            bot_status_element.append(buttons_block)
        }
        else{
            bot_status_element.empty();
            bot_status_element.append("<h3 class=\"float-left text-success\">{% trans "Running" context "Bot current status" %}</h3>");
            let buttons_block = $('<div />', {"class": 'button-container float-right mt-3'});
            buttons_block.append("<a class=\"btn btn-primary mb-0 mt-0 pl-2 pr-2\" href=\"#\" onclick=\"stop_bot()\">{% trans "Stop" context "Button for stopping bot" %}</a>");
            buttons_block.append("<a class=\"btn btn-primary mb-0 mt-0 pl-2 pr-2\" href=\"#\" onclick=\"restart_bot()\">{% trans "Restart" context "Button for restarting bot" %}</a>");
            bot_status_element.append(buttons_block)
        }
    }
};
socket.onopen = function(e){
    $.ajax({
        url: '{% url "website:bot_status" %}',
        method: "GET",
        dataType: 'json',
      });
$.ajax({
        url: '{% url "website:api_status" %}',
        method: "GET",
        dataType: 'json',
      })
};
</script>
{% endblock %}

website/templates/distribution.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "css/emojionearea.min.css" %}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="card">
                <div class="card-header card-header-primary">
                    <div class="float-left">
                        <h4 class="card-title">{% trans "Distribution" %}</h4>
                        <p class="card-category">{% trans "Enter message and press Send button" %}</p>
                    </div>
                </div>
                <div class="card-body">
                    <form id="distribution" action="{% url "website:start_distribution" %}">
                        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                        <div class="row">
                             <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                    <label class="bmd-label-floating" for="message-text">{% trans "Message" context "Message text for distribution" %}</label>
                                    <textarea class="form-control" id="message-text" name="text" rows="10"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                             <div class="col-12 col-md-6 offset-md-1 col-lg-12 d-flex">
                                <label class="switch">
                                  <input type="checkbox" name="web-preview" checked>
                                  <span class="slider round"></span>
                                </label>
                                    <p class="switch-text">{% trans "Web preview" context "Web preview switch for distribution message"%}</p>
                             </div>
                             <div class="col-12 col-md-5 col-lg-12 offset-lg-1 d-flex">
                                <label class="switch">
                                  <input type="checkbox" name="notification" checked>
                                  <span class="slider round"></span>
                                </label>
                                    <p class="switch-text">{% trans "Notification sound" context "Notification sound switch for distribution message" %}</p>
                                </div>
                            </div>

                            <div class="col-12 text-center">
                                <button type="submit" class="btn btn-primary" id="start_distribution">{% trans "Send" context "Send distribution message" %}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    </div>
{% endblock %}
{% block js %}
{{ block.super }}
<script type="text/javascript" src="{% static "js/emojionearea.min.js" %}"></script>

<script>
$(document).ready(function() {
    $("#message-text").emojioneArea({
        pickerPosition: "bottom"
        });
});
$("#distribution").submit(function (e) {
        e.preventDefault();
        var form = $(this);
        var url = form.attr('action');
        let text_input = $("#message-text");
         $.ajax({
           type: "POST",
           url: url,
           data: form.serialize(),
           success: function(data)
           {
               if (data['success'] === true){
                   text_input[0].emojioneArea.setText("");
               }
           }
         });
    }
);

var socket = new WebSocket(ws_scheme + "://" + window.location.host + "/ws/control");
socket.onmessage = function (e) {
    let data = JSON.parse(e.data);
    console.log(data);
    if (data['service'] === 'api' && data['status'] === false){
        $("#start_distribution").attr("disabled", true);
    }
};
socket.onopen = function(e){
    $.ajax({
        url: '{% url "website:api_status" %}',
        method: "GET",
        dataType: 'json',
      });
}
</script>
{% endblock %}

website/templates/navbar.html
{% load get from websitefilters %}
{% load i18n %}
{% load selected_bot from websitetags %}
{% get_available_languages as LANGUAGES %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute position-relative mb-4">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            {% if page_full_name %}
                <span class="navbar-brand">{{ page_full_name }}</span>
            {% else %}
                <span class="navbar-brand">{{ page_name }} - {% selected_bot %}</span>
            {% endif %}
            <span class="badge badge-pill badge-primary">Beta</span>
        </div>
        <div class="collapse navbar-collapse justify-content-end">
            {#            <form class="navbar-form">#}
            {#              <div class="input-group no-border">#}
            {#                <input type="text" value="" class="form-control" placeholder="Search...">#}
            {#                <button type="submit" class="btn btn-white btn-round btn-just-icon">#}
            {#                  <i class="material-icons">search</i>#}
            {#                  <div class="ripple-container"></div>#}
            {#                </button>#}
            {#              </div>#}
            {#            </form>#}
            <ul class="navbar-nav">
                {#              <li class="nav-item">#}
                {#                <a class="nav-link" href="#pablo">#}
                {#                  <i class="material-icons">dashboard</i>#}
                {#                  <p class="d-lg-none d-md-block">#}
                {#                    Stats#}
                {#                  </p>#}
                {#                </a>#}
                {#              </li>#}
                {#              <li class="nav-item dropdown">#}
                {#                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                {#                  <i class="material-icons">notifications</i>#}
                {#                  <span class="notification">5</span>#}
                {#                  <p class="d-lg-none d-md-block">#}
                {#                    Some Actions#}
                {#                  </p>#}
                {#                </a>#}
                {#                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">#}
                {#                  <a class="dropdown-item" href="#">Mike John responded to your email</a>#}
                {#                  <a class="dropdown-item" href="#">You have 5 new tasks</a>#}
                {#                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>#}
                {#                  <a class="dropdown-item" href="#">Another Notification</a>#}
                {#                  <a class="dropdown-item" href="#">Another One</a>#}
                {#                </div>#}
                {#              </li>#}
                <li class="nav-item">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}

                    {% for language in languages %}
                        <div class="d-inline-flex">
                        {% if language.code == LANGUAGE_CODE %}
                            <input type="submit" value="{{ language.code.upper }}" class="btn lang-nohover btn-dark disabled" disabled/>
                        {% else %}
                            <form action="{% url 'set_language' %}" method="post">
                                {% csrf_token %}
                                <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}"/>
                                <input name="language" type="hidden" value="{{ language.code }}"/>
                                <input type="submit" value="{{ language.code.upper }}" class="btn btn-dark btn-outline" />
                            </form>
                        {% endif %}
                        </div>
                    {% endfor %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="{% url "website:profile" %}">{% trans "Profile" %}</a>
                        {#                        <a class="dropdown-item" href="#">Settings</a>#}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url "website:logout" %}">{% trans "Log out" %}</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->